

Usage
-----

How to install Fyoo and run the CLI.

.. toctree::
    :maxdepth: 2

    usage


Building Flows
--------------

How to write your own Flows (consistent CLIs powered by Fyoo)!

.. toctree::
    :maxdepth: 2

    flow



API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
    :maxdepth: 2

    api

